spring:
  application:
    #配置服务名称
    name: order 
  #配置数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#配置Eureka
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/
#配置端扣号
server:
  port: 8802
#自定义负载均衡规则
#PRODUCT:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
env:
  dev4
girl: 
  name: lili
  age: 20
