spring:
  application:
    #配置服务名称
    name: product 
  #配置数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    #消息队列
  rabbitmq:
    host: 192.168.3.234
    username: guest
    password: guest
    port: 5672
# 配置Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#配置端扣号
server:
  port: 8804
